# Generated by Django 5.2.12 on 2026-03-06 19:13

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=30, verbose_name='telefone')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('avatar_url', models.URLField(blank=True, verbose_name='avatar URL')),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('client', 'Cliente'), ('inactive', 'Inativo')], default='lead', max_length=20, verbose_name='estágio')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='dados extras')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-created'],
                'unique_together': {('tenant', 'phone')},
            },
        ),
    ]
