# Generated by Django 5.2.12 on 2026-03-17 20:05

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_wa', '0001_initial'),
        ('contacts', '0001_initial'),
        ('conversations', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('tags_filter', models.JSONField(blank=True, default=list, help_text='Lista de tags — todos os contatos que possuam TODAS as tags. Vazio = todos.', verbose_name='filtro de tags')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendada'), ('running', 'Executando'), ('done', 'Concluída'), ('failed', 'Falhou')], default='draft', max_length=20, verbose_name='status')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='agendar para')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='enviados')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='total')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='channels_wa.whatsappsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='mensagem')),
                ('scheduled_at', models.DateTimeField(verbose_name='enviar em')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='status')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='contacts.contact')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='conversations.conversation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='channels_wa.whatsappsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Follow-up',
                'verbose_name_plural': 'Follow-ups',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
