# Generated by Django 5.2.12 on 2026-03-06 19:13

import django.core.validators
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nome da empresa')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/', verbose_name='logo')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='plano')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('max_bots', models.PositiveIntegerField(default=2, verbose_name='máx. bots')),
                ('max_sessions', models.PositiveIntegerField(default=1, verbose_name='máx. sessões WhatsApp')),
                ('max_messages_month', models.PositiveIntegerField(default=500, verbose_name='máx. mensagens/mês')),
                ('business_hours_start', models.TimeField(default='08:00', verbose_name='início atendimento')),
                ('business_hours_end', models.TimeField(default='18:00', verbose_name='fim atendimento')),
                ('out_of_hours_message', models.TextField(blank=True, default='Olá! Estamos fora do horário de atendimento. Retornaremos em breve.', verbose_name='mensagem fora do horário')),
                ('message_concat_delay', models.PositiveIntegerField(default=10, help_text='Tempo em segundos que o sistema aguarda novas mensagens do mesmo contato antes de processar. Útil para clientes que enviam mensagens em partes. Mínimo: 5s — Máximo: 60s.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)], verbose_name='delay de concatenação (segundos)')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
    ]
