# Generated by Django 5.2.12 on 2026-03-06 19:13

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nome do bot')),
                ('department', models.CharField(choices=[('sales', 'Vendas'), ('support', 'Suporte'), ('finance', 'Financeiro'), ('leads', 'Captação de Leads'), ('general', 'Geral')], default='general', max_length=20, verbose_name='departamento')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='bots/avatars/', verbose_name='avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('persona', models.TextField(blank=True, help_text='Descrição da personalidade do bot', verbose_name='persona')),
                ('capabilities', models.JSONField(blank=True, default=list, verbose_name='o que pode fazer')),
                ('restrictions', models.JSONField(blank=True, default=list, verbose_name='o que não pode fazer')),
                ('extra_instructions', models.TextField(blank=True, verbose_name='instruções extras')),
                ('model', models.CharField(default='gpt-4o', max_length=50, verbose_name='modelo OpenAI')),
                ('temperature', models.FloatField(default=0.7, verbose_name='temperatura')),
                ('max_tokens', models.PositiveIntegerField(default=500, verbose_name='máx. tokens resposta')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
                'ordering': ['tenant', 'name'],
            },
        ),
    ]
