# Generated by Django 5.0.6 on 2026-03-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='tools_enabled',
            field=models.BooleanField(default=False, help_text='Ativa function calling (ex: verificação de disponibilidade via Bookings)', verbose_name='ferramentas ativas'),
        ),
    ]
