# Generated by Django 5.2.12 on 2026-03-06 19:13

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('definition', models.JSONField(default=dict, verbose_name='definição do fluxo')),
                ('bot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow', to='bots.bot')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Flow',
                'verbose_name_plural': 'Flows',
                'ordering': ['tenant', 'name'],
            },
        ),
    ]
