# Generated by Django 5.0.6 on 2026-03-19 11:43

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_campaign_followup'),
        ('conversations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('category', models.CharField(help_text='Slug para agrupar recursos similares (ex: plataforma_360, cadeira)', max_length=100, verbose_name='categoria')),
                ('booking_type', models.CharField(choices=[('full_day', 'Dia inteiro'), ('time_slot', 'Horário específico')], default='full_day', max_length=20, verbose_name='tipo de reserva')),
                ('max_bookings_per_day', models.PositiveIntegerField(default=1, help_text='Quantos agendamentos simultâneos este recurso aceita no mesmo dia', verbose_name='máx. reservas por dia')),
                ('slot_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Apenas para tipo Horário específico', null=True, verbose_name='duração do slot (min)')),
                ('working_hours_start', models.TimeField(blank=True, null=True, verbose_name='início do expediente')),
                ('working_hours_end', models.TimeField(blank=True, null=True, verbose_name='fim do expediente')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['tenant', 'category', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateField(verbose_name='data do evento')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='horário início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='horário fim')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='status')),
                ('client_name', models.CharField(blank=True, help_text='Preenchido quando não há Contact vinculado', max_length=200, verbose_name='nome do cliente')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='contacts.contact')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='conversations.conversation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tenants.tenant')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.resource')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-event_date', 'resource'],
            },
        ),
    ]
