# Generated by Django 5.2.12 on 2026-03-06 19:13

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nome da sessão')),
                ('instance_id', models.CharField(max_length=200, unique=True, verbose_name='instance ID UazAPI')),
                ('token', models.CharField(max_length=500, verbose_name='token UazAPI')),
                ('status', models.CharField(choices=[('disconnected', 'Desconectado'), ('connecting', 'Conectando'), ('connected', 'Conectado'), ('error', 'Erro')], default='disconnected', max_length=20, verbose_name='status')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='número WhatsApp')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_sessions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Sessão WhatsApp',
                'verbose_name_plural': 'Sessões WhatsApp',
                'ordering': ['tenant', 'name'],
            },
        ),
    ]
