# Generated by Django 5.2.12 on 2026-03-06 19:13

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        ('channels_wa', '0001_initial'),
        ('contacts', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('bot', 'Bot'), ('human', 'Humano'), ('pending', 'Pendente'), ('closed', 'Encerrado')], default='bot', max_length=20, verbose_name='status')),
                ('current_flow_node', models.CharField(blank=True, max_length=100, verbose_name='nó atual do flow')),
                ('context', models.JSONField(blank=True, default=list, verbose_name='contexto OpenAI')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='não lidas')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='última mensagem')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='bots.bot')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='contacts.contact')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='channels_wa.whatsappsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída')], max_length=5, verbose_name='direção')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('is_concatenated', models.BooleanField(default=False, verbose_name='concatenada')),
                ('wa_message_id', models.CharField(blank=True, max_length=200, verbose_name='ID WhatsApp')),
                ('media_url', models.URLField(blank=True, verbose_name='URL mídia')),
                ('media_type', models.CharField(blank=True, max_length=20, verbose_name='tipo mídia')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created'],
            },
        ),
    ]
